AllCops:
  NewCops: enable
  Exclude:
    - "config/initializers/jwt_authenticatable.rb"
    - "db/schema.rb"
    - "bin/bundle"
    - "config/**/*"

Layout/LineLength:
  Exclude:
    - "spec/**/*"
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
  Enabled: true

Style/Documentation:
  Exclude:
    - "**/*"
  Enabled: true

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: true

Layout/LineContinuationLeadingSpace:
  Enabled: true

Layout/LineContinuationSpacing:
  Enabled: true

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousOperatorPrecedence:
  Enabled: true

Lint/AmbiguousRange:
  Enabled: true

Lint/ConstantOverwrittenInRescue:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateMagicComment:
  Enabled: true

Lint/DuplicateMatchPattern:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/EmptyInPattern:
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true

Lint/ItWithoutArgumentsInBlock:
  Enabled: true
