inherit_from: .rubocop_todo.yml

require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - "config/initializers/jwt_authenticatable.rb"
    - "db/schema.rb"
    - "bin/bundle"
    - "config/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Exclude:
    - "spec/**/*"
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
  Enabled: true

Style/Documentation:
  Exclude:
    - "**/*"
  Enabled: true

Rails/DuplicateAssociation:
  Enabled: false

RSpecRails/AvoidSetupHook:
  Enabled: false

RSpecRails/HttpStatus:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false

RSpecRails/MinitestAssertions:
  Enabled: false

RSpecRails/TravelAround:
  Enabled: false

RSpecRails/NegationBeValid:
  Enabled: false
