AllCops:
  Exclude:
    - "config/initializers/jwt_authenticatable.rb"
    - "db/schema.rb"
    - "bin/bundle"
    - "config/**/*"

Layout/LineLength:
  Exclude:
    - "spec/**/*"
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
  Enabled: true

Style/Documentation:
  Exclude:
    - "**/*"
  Enabled: true
