version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5433"
    expose:
      - "5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -p 5433

volumes:
  postgres_data:
    driver: local
